export const levels = [
  {
    years: 'Prima superiore',
    title: 'L\'inizio della campagna',
    phase: 'Adattamento',
    text1: 'Leonardo ha 14 anni, cresce in campagna e ogni giorno entra nella sua personale "grande metropoli" per frequentare il Liceo Scientifico Scienze Applicate all\'I.I.S. Ettore Majorana. Parte con entusiasmo, attratto dalle materie scientifiche e dall\'idea di costruire un percorso che senta davvero suo.',
    text2: 'Ma il primo ostacolo è capire che la campagna non si vince solo con ciò che piace di più. Alle lezioni si aggiungono allenamenti intensi e gare di nuoto pinnato ad alto livello: serve amministrare energie, come in una vasca lunga in cui partire forte non basta, bisogna sapersi regolare.',
    tags: ['Entusiasmo', 'Scienze', 'Disciplina', 'Gestione del tempo'],
    question: 'Come bilancereste studio e allenamenti senza sacrificare né rendimento né salute?',
    choices: [
      'Creare una routine rigida e costante.',
      'Dare priorità alle scadenze settimana per settimana.',
      'Usare lo sport come allenamento mentale anche per la scuola.',
    ],
    feedback: 'Qualunque scelta faccia la commissione, il punto chiave è questo: qui nasce la disciplina. Leonardo inizia a capire che talento e passione funzionano solo se accompagnati da metodo.',
  },
  {
    years: 'Terza superiore',
    title: 'Primo punto di svolta',
    phase: 'Apertura agli altri',
    text1: 'In terza superiore l\'eroe cambia prospettiva. Entra nel progetto STUDENTI TUTOR – PROGETTO ACCOGLIENZA CLASSI PRIME e smette di guardare la scuola solo dal proprio banco: inizia ad aiutare chi arriva, a orientare, rassicurare e comunicare con più attenzione.',
    text2: 'Nello stesso periodo affronta una missione speciale nei Campionati italiani assoluti di nuoto pinnato, dove conquista la prima medaglia d\'oro italiana assoluta nella 4×100 monopinna. È un passaggio importante: dalla prestazione personale alla responsabilità condivisa, sia nello sport sia nella scuola.',
    tags: ['Empatia', 'Responsabilità', 'Comunicazione', 'Spirito di squadra'],
    question: 'Come si può trasformare una vittoria sportiva in motivazione reale anche nello studio?',
    choices: [
      'Usandola come prova concreta che l\'impegno produce risultati.',
      'Trasferendo la stessa costanza dell\'allenamento nei compiti scolastici.',
      'Leggendola come successo del gruppo, non solo del singolo.',
    ],
    feedback: 'Questo livello mostra che la crescita non è solo interiore: Leonardo diventa più affidabile verso gli altri e comprende che una vittoria conta davvero quando cambia anche il proprio atteggiamento quotidiano.',
  },
  {
    years: 'Quarta superiore',
    title: 'La svolta scientifico-professionale',
    phase: 'Scienza applicata',
    text1: 'Con la FSL Dermosfera, Leonardo lavora in gruppo alla realizzazione di Cannabliss Care, una linea di cosmetici a base di CBD pensata per pelle, igiene, capelli e sport. Il progetto richiede organizzazione, divisione dei ruoli, attenzione al target e cura del packaging.',
    text2: 'Qui la scienza esce dal quaderno ed entra nella vita concreta delle persone. Chimica, osservazione e progettazione si intrecciano con il mondo del lavoro: non più solo teoria, ma idee da rendere comprensibili, utili e presentabili.',
    tags: ['Teamwork', 'Progettazione', 'Target', 'Packaging'],
    question: 'Quali competenze trasversali riconoscete in un\'esperienza FSL di tipo scientifico/commerciale?',
    choices: [
      'Collaborazione e suddivisione efficace dei ruoli.',
      'Capacità di collegare teoria scientifica e bisogni reali.',
      'Comunicazione di prodotto e attenzione al pubblico.',
    ],
    feedback: 'La missione Dermosfera gli insegna che la competenza scientifica vale di più quando sa dialogare con realtà, utenti e contesti concreti.',
  },
  {
    years: 'Quarta–quinta superiore',
    title: 'La svolta interiore e civica',
    phase: 'Sguardo sul mondo',
    text1: 'Tra quarta e quinta, Leonardo inizia a interessarsi seriamente alla politica attuale e alla vita civile. Questa curiosità allarga il suo orizzonte: la domanda non è più solo "come funziona un fenomeno?", ma anche "come funziona una società?".',
    text2: 'È qui che cambiano anche le materie umanistiche. Storia, filosofia e italiano non sono più semplici materie da voto, ma strumenti per leggere il presente, interpretare le idee e comprendere la dimensione umana che la scienza da sola non basta a spiegare.',
    tags: ['Cittadinanza', 'Curiosità', 'Storia', 'Filosofia'],
    question: 'Quanto è importante che uno studente scientifico sviluppi anche uno sguardo umanistico?',
    choices: [
      'È fondamentale per capire il contesto umano della conoscenza.',
      'È utile per argomentare meglio e leggere la complessità.',
      'È una forma di equilibrio tra rigore e sensibilità.',
    ],
    feedback: 'In questa tappa Leonardo non abbandona la scienza: la completa. Impara che capire il mondo significa saper tenere insieme dati, idee, persone e istituzioni.',
  },
  {
    years: 'Quinta superiore',
    title: 'L\'eroe si espone e guarda oltre',
    phase: 'Partecipazione',
    text1: 'In quinta Leonardo decide di esporsi: si candida come rappresentante di istituto, entra in un\'organizzazione politica giovanile e partecipa alla Giornata di formazione a Montecitorio. Non osserva più soltanto la vita pubblica: sceglie di entrarci, conoscerla da vicino e assumersi una responsabilità visibile.',
    text2: 'A questa crescita si affianca una quest multipla: Giochi della Chimica, Campionati italiani di Fisica – gara di secondo livello, e Olimpiadi di Matematica. Sono prove che allenano rigore logico, problem solving e resistenza mentale, come serie diverse di uno stesso allenamento.',
    text3: 'In quinta Leonardo compie anche una scelta silenziosa ma concreta: si iscrive al registro dei donatori di midollo osseo. È un gesto che non porta visibilità, ma che ha un impatto reale sulla vita di altre persone.',
    tags: ['Rappresentanza', 'Democrazia', 'Problem solving', 'Rigore logico'],
    question: 'Che ruolo hanno partecipazione, rappresentanza e competizioni nella crescita di uno studente?',
    choices: [
      'Aiutano a uscire da una logica passiva.',
      'Allenano responsabilità, coraggio e capacità di confronto.',
      'Trasformano le conoscenze in esperienza concreta.',
    ],
    feedback: 'Qui l\'eroe smette definitivamente di restare sullo sfondo. Diventa presenza attiva, riferimento nella scuola e persona capace di mettersi in gioco davanti agli altri.',
  },
  {
    years: 'Scelta universitaria e maturità',
    title: 'La boss fight finale',
    phase: 'Decisione',
    text1: 'Arriva il momento critico: scegliere tra Chimica dei materiali e Fisica. La chimica richiama l\'esperienza del PCTO e i Giochi della Chimica; la fisica richiama le gare, la ricerca e il desiderio di capire i meccanismi più profondi della realtà.',
    text2: 'La conferenza ALICE diventa il punto di svolta: è il momento in cui Leonardo capisce che la sua strada sarà Fisica. E così tutte le missioni precedenti — sport, tutoraggio, attività civiche, olimpiadi, interessi umanistici — convergono nella vera boss fight finale: l\'esame di maturità.',
    tags: ['Orientamento', 'Ricerca', 'Scelta', 'Consapevolezza'],
    question: 'Se doveste consigliare un percorso universitario, quali criteri usereste per scegliere bene?',
    choices: [
      'La passione autentica e la curiosità che dura nel tempo.',
      'Le esperienze concrete già vissute e ciò che hanno rivelato.',
      'L\'equilibrio tra attitudine personale e prospettive future.',
    ],
    feedback: 'La scelta finale non nasce da un\'intuizione improvvisa, ma dalla somma di tutte le prove precedenti. Il vero risultato è arrivare alla maturità sapendo non solo cosa si vuole studiare, ma chi si è diventati.',
  },
]
